services:
  - type: web
    name: novatrust-bank
    env: php
    plan: free

    disk:
      name: uploads
      mountPath: /var/www/html/storage/app/public
      sizeGB: 1

    buildCommand: |
      composer install
      php artisan key:generate --force
      php artisan storage:link

    startCommand: ./start.sh

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: novatrust-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: novatrust-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: novatrust-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: novatrust-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: novatrust-db
          property: password
 
databases:
  - name: novatrust-db
    plan: free
